// Code generated by mgufrone.dev/job-alerts/cmd/generate-domain, DO NOT EDIT.
package user

import (
	uuid "github.com/google/uuid"
	try "github.com/mgufrone/go-utils/try"
)

func New(id uuid.UUID, authID string, status Status, roles []string) (ent *Entity, err error) {
	var res Entity
	err = try.RunOrError(func() error {
		return res.SetID(id)
	}, func() error {
		return res.SetAuthID(authID)
	}, func() error {
		return res.SetStatus(status)
	}, func() error {
		return res.SetRoles(roles)
	})
	if err == nil {
		ent = &res
	}
	return
}
