// Code generated by mgufrone.dev/job-alerts/cmd/generate-domain, DO NOT EDIT.
package user

import (
	"encoding/json"
	jsonparser "github.com/buger/jsonparser"
	try "github.com/mgufrone/go-utils/try"
	helpers "mgufrone.dev/job-alerts/pkg/helpers"
)

func (e *Entity) UnmarshalJSON(data []byte) error {
	return try.RunOrError(func() error {
		val, err := helpers.GetUUID(data, "id")
		if err != nil {
			return err
		}
		return e.SetID(val)
	}, func() error {
		val, err := jsonparser.GetString(data, "authID")
		if err != nil {
			return err
		}
		return e.SetAuthID(val)
	}, func() error {
		val, err := jsonparser.GetInt(data, "status")
		if err != nil {
			return err
		}
		return e.SetStatus(Status(val))
	}, func() error {
		var res []string
		_, err := jsonparser.ArrayEach(data, func(value []byte, dataType jsonparser.ValueType, offset int, err error) {
			res = append(res, string(value))
		}, "roles")
		if err != nil {
			return err
		}
		return e.SetRoles(res)
	})
}
func (e *Entity) MarshalJSON() ([]byte, error) {
	res := map[string]interface{}{
		"id":     e.ID(),
		"authID": e.AuthID(),
		"status": int(e.Status()),
		"roles":  e.Roles(),
	}
	return json.Marshal(res)
}
