// Code generated by mgufrone.dev/job-alerts/cmd/generate-domain, DO NOT EDIT.
package job

import (
	"github.com/google/uuid"
	try "github.com/mgufrone/go-utils/try"
	"time"
)

func New(id uuid.UUID, role string, companyName string, companyURL string, description string, jobURL string, tags []string, location string, source string, jobType string, isRemote bool, salary []float64, salaryCurrency string, createdAt time.Time, updatedAt time.Time) (ent *Entity, err error) {
	var res Entity
	err = try.RunOrError(func() error {
		return res.SetID(id)
	}, func() error {
		return res.SetRole(role)
	}, func() error {
		return res.SetCompanyName(companyName)
	}, func() error {
		return res.SetCompanyURL(companyURL)
	}, func() error {
		return res.SetDescription(description)
	}, func() error {
		return res.SetJobURL(jobURL)
	}, func() error {
		return res.SetTags(tags)
	}, func() error {
		return res.SetLocation(location)
	}, func() error {
		return res.SetSource(source)
	}, func() error {
		return res.SetJobType(jobType)
	}, func() error {
		return res.SetIsRemote(isRemote)
	}, func() error {
		return res.SetSalary(salary)
	}, func() error {
		return res.SetSalaryCurrency(salaryCurrency)
	}, func() error {
		return res.SetCreatedAt(createdAt)
	}, func() error {
		return res.SetUpdatedAt(updatedAt)
	})
	if err == nil {
		ent = &res
	}
	return
}
