package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"fmt"

	"mgufrone.dev/job-alerts/delivery/graphql/graph/model"
)

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, input model.NewChannel) (*model.NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: CreateChannel - createChannel"))
}

// Channels is the resolver for the channels field.
func (r *queryResolver) Channels(ctx context.Context, filter *model.NotificationFilter, page *model.Pagination) (*model.NotificationResult, error) {
	panic(fmt.Errorf("not implemented: Channels - channels"))
}
