// Code generated by mgufrone.dev/job-alerts/cmd/generate-domain, DO NOT EDIT.
package user_channel

import (
	uuid "github.com/google/uuid"
	try "github.com/mgufrone/go-utils/try"
	user "mgufrone.dev/job-alerts/internal/domain/user"
	"time"
)

func New(id uuid.UUID, user *user.Entity, channelType string, receiver string, createdAt time.Time, updatedAt time.Time) (ent *Entity, err error) {
	var res Entity
	err = try.RunOrError(func() error {
		return res.SetID(id)
	}, func() error {
		return res.SetUser(user)
	}, func() error {
		return res.SetChannelType(channelType)
	}, func() error {
		return res.SetReceiver(receiver)
	}, func() error {
		return res.SetCreatedAt(createdAt)
	}, func() error {
		return res.SetUpdatedAt(updatedAt)
	})
	if err == nil {
		ent = &res
	}
	return
}
