// Code generated by mgufrone.dev/job-alerts/cmd/generate-domain, DO NOT EDIT.
package notification

import (
	"encoding/json"
	jsonparser "github.com/buger/jsonparser"
	uuid "github.com/google/uuid"
	try "github.com/mgufrone/go-utils/try"
	channel "mgufrone.dev/job-alerts/internal/domain/channel"
	job "mgufrone.dev/job-alerts/internal/domain/job"
	user "mgufrone.dev/job-alerts/internal/domain/user"
	helpers "mgufrone.dev/job-alerts/pkg/helpers"
)

func (e *Entity) UnmarshalJSON(data []byte) error {
	return try.RunOrError(func() error {
		val, err := helpers.GetUUID(data, "id")
		if err != nil {
			return err
		}
		return e.SetID(val)
	}, func() error {
		var ref user.Entity
		val, err := helpers.GetUUID(data, "userID")
		if err != nil {
			return err
		}
		if val == uuid.Nil {
			return nil
		}
		roles, err := jsonparser.GetString(data, "user_roles")
		if err != nil {
			return err
		}
		if roles != "" {
			_ = ref.SetRoles([]string{roles})
		}
		_ = ref.SetID(val)
		return e.SetUser(&ref)
	}, func() error {
		var ref job.Entity
		val, err := helpers.GetUUID(data, "jobID")
		if err != nil {
			return err
		}
		if val == uuid.Nil {
			return nil
		}
		_ = ref.SetID(val)
		return e.SetJob(&ref)
	}, func() error {
		var ref channel.Entity
		val, err := helpers.GetUUID(data, "channelID")
		if err != nil {
			return err
		}
		if val == uuid.Nil {
			return nil
		}
		_ = ref.SetID(val)
		return e.SetChannel(&ref)
	}, func() error {
		val, err := jsonparser.GetBoolean(data, "isSent")
		if err != nil {
			return err
		}
		return e.SetIsSent(val)
	}, func() error {
		val, err := helpers.GetTime(data, "sentAt")
		if err != nil {
			return err
		}
		return e.SetSentAt(val)
	}, func() error {
		val, err := helpers.GetTime(data, "readAt")
		if val.IsZero() || err != nil {
			return nil
		}
		return e.SetReadAt(&val)
	}, func() error {
		val, err := helpers.GetTime(data, "createdAt")
		if err != nil {
			return err
		}
		return e.SetCreatedAt(val)
	}, func() error {
		val, err := helpers.GetTime(data, "updatedAt")
		if err != nil {
			return err
		}
		return e.SetUpdatedAt(val)
	})
}
func (e *Entity) MarshalJSON() ([]byte, error) {
	res := map[string]interface{}{
		"id": e.ID(),
		"user_roles": func() string {
			if e.User() == nil || len(e.User().Roles()) == 0 {
				return ""
			}
			return e.User().Roles()[0]
		}(),
		"userID": func() uuid.UUID {
			if e.User() == nil {
				return uuid.Nil
			}
			return e.User().ID()
		}(),
		"jobID":     e.Job().ID(),
		"channelID": e.Channel().ID(),
		"isSent":    e.IsSent(),
		"sentAt":    e.SentAt().UnixMilli(),
		"readAt": func() interface{} {
			if e.ReadAt() == nil {
				return nil
			}
			return e.ReadAt().UnixMilli()
		}(),
		"createdAt": e.CreatedAt().UnixMilli(),
		"updatedAt": e.UpdatedAt().UnixMilli(),
	}
	return json.Marshal(res)
}
